const mongoose = require("mongoose");

const vehicleSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, "A product must have a name"],
      unique: true,
      trim: true,
      maxlength: [
        30,
        "A product name must have less or equal than 30 characters",
      ],
      minlength: [5, "A product name have more or equal than 5 characters"],
    },
    vehicle_brand: {
      type: String,
      enum: [
        "Toyota",
        "Honda",
        "Ford",
        "Chevrolet",
        "Nissan",
        "BMW",
        "Mercedes-Benz",
        "Audi",
        "Volkswagen",
        "Hyundai",
        "Kia",
        "Tesla",
        "Subaru",
        "Mazda",
        "Volvo",
        "Land Rover",
        "Jaguar",
        "Porsche",
        "Ferrari",
        "Lamborghini",
        "Bugatti",
        "Rolls-Royce",
        "Bentley",
        "Aston Martin",
        "McLaren",
        "Harley-Davidson",
        "Yamaha",
        "Kawasaki",
        "Suzuki",
        "Ducati",
        "KTM",
        "Triumph",
        "Royal Enfield",
        "Aprilia",
        "BMW Motorrad",
        "Volvo Trucks",
        "Scania",
        "MAN",
        "Freightliner",
        "Kenworth",
        "Peterbilt",
        "Mack Trucks",
        "Isuzu",
        "Iveco",
        "Hino",
        "Rivian",
        "Lucid Motors",
        "Polestar",
        "BYD",
        "VinFast",
      ],
      default: "Motors",
    },
    color: {
      type: String,
      enum: [
        "Red",
        "Blue",
        "Green",
        "Yellow",
        "Orange",
        "Purple",
        "Pink",
        "Brown",
        "Black",
        "White",
        "Gray",
        "Cyan",
        "Magenta",
        "Turquoise",
        "Teal",
        "Lime",
        "Olive",
        "Maroon",
        "Navy",
        "Beige",
        "Coral",
        "Gold",
        "Silver",
        "Bronze",
        "Ivory",
        "Lavender",
        "Violet",
        "Indigo",
        "Crimson",
        "Scarlet",
        "Ruby",
        "Sapphire",
        "Emerald",
        "Aquamarine",
        "Peach",
        "Mustard",
        "Periwinkle",
        "Lilac",
        "Amber",
        "Mauve",
        "Tan",
        "Charcoal",
        "Mint",
        "Plum",
        "Burgundy",
        "Rose",
        "Sky Blue",
        "Chocolate",
        "Copper",
        "Sand",
        "Khaki",
        "Azure",
        "Baby Blue",
        "Blush",
        "Cherry",
        "Cinnamon",
        "Cloud",
        "Cobalt",
        "Denim",
        "Ebony",
        "Fawn",
        "Flamingo",
        "Fuchsia",
        "Glacier",
        "Grape",
        "Honey",
        "Ivory Cream",
        "Jade",
        "Jasmine",
        "Juniper",
        "Lemon",
        "Licorice",
        "Mahogany",
        "Mango",
        "Maple",
        "Mocha",
        "Mulberry",
        "Ocean",
        "Onyx",
        "Opal",
        "Papaya",
        "Pastel Green",
        "Pastel Pink",
        "Peacock",
        "Pewter",
        "Pine",
        "Raspberry",
        "Rust",
        "Saffron",
        "Sage",
        "Sapphire Blue",
        "Seashell",
        "Sepia",
        "Slate",
        "Smoke",
        "Snow",
        "Steel Blue",
        "Sunset",
        "Tangerine",
        "Vanilla",
        "Velvet",
        "Vermilion",
        "Walnut",
        "Wine",
        "Zinc",
        "Zaffre",
      ],
      default: "White",
    },
    vehicle_model: {
      type: String,
    },
    price: {
      type: Number,
      required: [true, "A vehicle must have a price"],
      min: [0, "Price cannot be negative"],
    },
    negotiable: Boolean,
    bookmarks: {
      type: Number,
      default: 1,
    },
    views: {
      type: Number,
      default: 1,
    },
    primarySpecifications: [
      {
        specType: {
          type: String,
          enum: [
            "transmission",
            "fuel_type",
            "usage",
            "trimming",
            "sound system",
            "seat_material",
            "air_conditioning",
            "steering_controls",
            "phone_connectivity",
            "auto_start_and_stop",
            "infotainment_system",
            "isofix_child_seat_anchors",
            "fm_radio_with_bluetooth_aux_and_usb",
            "keyless_entry_and_push_button_start",
          ],
          default: "usage",
        },
        value: {
          type: String,
          required: true,
          maxlength: [
            20,
            "A product name must have less or equal than 20 characters",
          ],
          minlength: [3, "A product name have more or equal than 3 characters"],
          trim: true,
        },
      },
    ],
    specifications: [
      {
        specType: {
          type: String,
          enum: ["make", "model", "usage", "drivetrain", "engine_size", "trim"],
          default: "usage",
        },
        value: {
          type: String,
          required: true,
          maxlength: [
            20,
            "A vehicle specifications must have less or equal than 20 characters",
          ],
          minlength: [
            3,
            "A vehicle specifications have more or equal than 3 characters",
          ],
          trim: true,
        },
      },
    ],
    description: {
      type: String,
      trim: true,
    },
    markUnavailable: Boolean,
    report_abuse: Boolean,
    bodyType: {
      type: String,
      enum: [
        "SUVs",
        "Saloons",
        "Hatchbacks",
        "Pickup",
        "Cabriolet/convertibles",
        "Van",
      ],
    },
    location: {
      type: {
        type: String,
        default: "Point",
        enum: ["Point"],
      },
      coordinates: [Number],
      address: String,
      images: [String],
      description: String,
    },
    seller: {
      type: mongoose.Schema.ObjectId,
      ref: "User",
      required: [true, "Must have a user"],
    },
    coverImage: String,
    coverVideo: String,
    images: [String],
  },
  {
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

const Vehicle = mongoose.model("vehicle", vehicleSchema);

module.exports = Vehicle;
